protocol = "ni-daqmx-tmux"
doc = "Triggered NI-daqmx with multiplex."
traits = ["is-sensor", "has-measure-trigger", "is-daemon"]
hardware = ["ni:pci-6251"]

[links]
source = ""
bugtracker = ""
manufacturer = ""

[installation]
PyPI = "https://pypi.org/project/yaqd-ni"

[[types]]
type = "enum"
name = "processing_method"
symbols = ["average", "sum", "min", "max"]
default = "average"

[[types]]
type = "record"
name = "channel"
fields = [{"name"="name", "type"="string"},
          {"name"="range", "type"="string"},
          {"name"="enabled", "type"="boolean", "default"=true},
	  {"name"="invert", "type"="boolean", "default"=false},
	  {"name"="signal_start", "type"="int"},
	  {"name"="signal_stop", "type"="int"},
	  {"name"="signal_presample", "type"="int", default=0},
	  {"name"="signal_method", "type"="processing_method"},
	  {"name"="use_baseline", "type"="boolean", "default"=false},
	  {"name"="baseline_start", "type"=["null", "int"], "default"="__null__"},
	  {"name"="baseline_stop", "type"=["null", "int"], "default"="__null__"},
	  {"name"="baseline_presample", "type"="int", default=0},
	  {"name"="baseline_method", "type"="processing_method"}]

[[types]]
type = "record"
name = "chopper"
fields = [{"name"="name", "type"="string"},
          {"name"="enabled", "type"="boolean", "default"=true},
	  {"name"="invert", "type"="boolean", "default"=false},
	  {"name"="index", "type"="int"}]

[config]

[config.device_name]
type = "string"
doc = "DAQmx name of device to address."

[config.trigger_source]
type = "string"
default = "ai0"

[config.nsamples]
type = "int"
default = 900

[config.timeout]
type = "float"
default = 10.0
doc = "Timeout in seconds between each trigger edge."

[config.rest_channel]
type = "string"
default = "ai0"
doc = "Channel to occupy when not making an explicitly specified measurement."

[config.channels]
type = "map"
values = "channel"
default = {}

[config.choppers]
type = "map"
values = "chopper"
default = {}

[config.shots_processing_script]
type = ["null", "string"]
doc = "Path to script for shots processing."
default = "__null__"

[state]

[state.nshots]
type = "int"
default = 100

[messages]

[messages.get_measured_samples]
response = "ndarray"
doc = "Get an array of shape (sample, shot)."

[messages.get_measured_shots]
response = "ndarray"

[messages.get_nshots]
doc = "Get the currently planned number of shots."
response = "int"

[messages.set_nshots]
doc = "Set the number of shots to acquire."
request = [{"name"="nshots", "type"="int"}]

[messages.get_sample_correspondances]
doc = "Returns an array of integers of length nsamples. Zero indicates rest sample. Postive indicates channel. Negative indicates chopper."
response = "ndarray"

